account/urls.py
from django.urls import path
from account.views import RegisterManagerView, RegisterCustomer, LoginView, RegisterBranchEmployeeView, RegisterChaeffeurView, RegisterDamageExpert
from manager.views import *

urlpatterns = [
    path('signupCustomer/', RegisterCustomer.as_view(), name='customer_register'),
    path('signupBranchEmployee/', RegisterBranchEmployeeView.as_view(), name='branchemployee-register'),
    path('signupChaeffur/', RegisterChaeffeurView.as_view(), name='chauffeur-register'),
    path('signupDamageExpert/', RegisterDamageExpert.as_view(), name='damageexpert-register'),
    path('signupManager/', RegisterManagerView.as_view(), name='manager-register'),
    path('login/', LoginView.as_view(), name='login_user')
]

car_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('customer/', include('customer.urls')),
                  path('accounts/', include('account.urls')),
                  path('employee/', include('employee.urls')),
                  path('chauffeur/', include('chauffeur.urls')),
                  path('management/', include('manager.urls', namespace='manager')),
                  path('damage_expert/', include('damage_expert.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customer/urls.py
from django.urls import path
from customer.views import PenaltiesView, cancelReservation, OrderReservations, CustomerDashboard, MakeReservation, RateCar, CreateRequest, RateBranch, ReturnVehicle, PayVehicle, ListReservations, ReservationComplate, Error, DateError

from django.contrib.auth.views import LogoutView



app_name = 'customer'
urlpatterns = [
    path('customerDashboard/', CustomerDashboard.as_view(), name='customer_dashboard'),
    path('penalties/', PenaltiesView.as_view(), name='customer-penalties'),
    path('rateVehicle/', RateCar.as_view(), name='customer_rate_vehicle'),
    path('rateBranch/', RateBranch.as_view(), name='customer_rate_branch'),
    path('error/', Error.as_view(), name='customer_error'),
    path('errorDate', DateError.as_view(), name='customer_date_error'),
    path('reservationsuccess/', ReservationComplate.as_view(), name='customer_reservation_complate'),
    path('returnVehicle/', ReturnVehicle.as_view(), name='customer_return_vehicle'),
    path('createRequest/', CreateRequest.as_view(), name='customer_create_request'),
    path('makereservation/', MakeReservation.as_view(), name='customer_make_res'),
    path('payVehicle/<str:resno>', PayVehicle.as_view(), name='customer_pay_vehicle'),
    path('allReservations/', ListReservations.as_view(), name='reservation_list'),
    path('makereservation/<str:plate>', MakeReservation.as_view(), name='customer_make_res'),
    path('orderReservations/', OrderReservations.as_view(), name='order_reservations'),
    path('ajax/cancelReservation/', cancelReservation, name='ajax_cancel_reservation'),
    path("logout/", LogoutView.as_view(), name="logout")
]

employee/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from employee.views import *

app_name = 'employee'
urlpatterns = [
    path('employeeDashboard/<int:employee_id>', EmployeeMainPage.as_view(), name='employee-dashboard'),
    path('employeeReservations/', ReservationView.as_view(), name='view-reservations'),
    path('ajaxAcceptReservation/', accept_reservation, name='accept-reservation'),
    path('ajaxDeclineReservation/', decline_reservation, name='decline-reservation'),
    path('ajaxAcceptRequest/', accept_request, name='accept-request'),
    path('ajaxDeclineRequest/', decline_request, name='decline-request'),
    path('employeeRequests/', RequestsView.as_view(), name='view-requests'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('branchCars/<int:branch_id>', BranchCarView.as_view(), name='cars_at_branch'),
    path('filterReservations/', FilterReservations.as_view(), name='filter_customer_reservations'),
    path('filterVehicle/', FilterVehicles.as_view(), name='filter_vehicle_branch')
]

templates/baseEmployee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Employee</title>

</head>
<style>

</style>
{% block style %}
{% endblock %}
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
            <a href="{% url 'employee:view-reservations' %}">
            <img src="{% static 'icon.png' %}" alt="" width="50" height="50" class="d-inline-block align-text-top"> </a>
            <a class="navbar-brand" href="{% url 'employee:view-reservations' %}">CaRent</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/employee/branchCars/{{ branch_id }}">{{ branch_name }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'employee:view-reservations' %}">Reservations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'employee:view-requests' %}">Requests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'employee:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
        {% block content %}
        {% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">


</script>
{% block scripts %}
{% endblock %}
</html>

templates/branchCarsEmployee.html
{% extends 'baseEmployee.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Vehicles at {{ branch_name }}</h1>
                    <form class="form-inline" role="form" action="{% url 'employee:filter_vehicle_branch' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="sr-only" for="name">Enter License Plate</label>
                            <input name="license" type="text" class="form-control" id="name" placeholder="License Plate">
                            <input type="hidden" value="{{ vehicles }}" id="vehicles">
                        </div>
                    <select name='age-vehicle' class="custom-select my-1 mr-sm-2" id="car-age">
                        <option value="-1">Age</option>
                        <option value="0">0-5</option>
                        <option value="6">6-10</option>
                        <option value="11">11-15</option>
                        <option value="16">15-20</option>
                        <option value="21">More than 20</option>
                    </select>
                    <select name='model-vehicle' class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                        <option value="empty" selected>Model</option>
                        {% for model in models %}
                            <option value={{ model }}>{{ model }}</option>
                        {% endfor %}
                    </select>
                    <select name="kilometers" class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                        <option selected value="-1">Kilometers</option>
                        <option value="0">0-5000</option>
                        <option value="5000">5000-10000</option>
                        <option value="10000">10000-20000</option>
                         <option value="20000">20000-40000</option>
                         <option value="40000">40000-more</option>
                    </select>
                    <select name='brand' class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                        <option value="empty" selected>Brand</option>
                         {% for brand in brands %}
                            <option value={{ brand }}>{{ brand }}</option>
                        {% endfor %}
                    </select>
                    <br>
                      <label class="sr-only" for="name">Enter Lowest Rent Price</label>
                    <input name="lowest" type="number" class="form-control" value="0" min="0">
                     <label class="sr-only" for="name">Enter Highest Rent Price</label>
                     <input name="highest" type="number" class="form-control" value="0" min="0">
                        <button style="margin:15px" type="submit" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
           {% for car in vehicles %}
                {% if forloop.counter|divisibleby:"5" %}
                    <div class="row mt-4">
                                    <div class="col-sm">
                    <img style="text-align: center;" src="{% static 'car1.jpeg' %}" width="150" height="150"
                        alt="">
                    <p class="mt-2 m-1 "><b>Plate: </b>{{ car.0 }}</p>
                    <p class="m-1"><b>Daily Price: </b> {{ car.2}}</p>
                    <p class="m-1"><b>Model: </b>{{ car.3 }}</p>
                    <p class="m-1"><b>Age: </b>{{ car.6 }}</p>
                    <p class="m-1"><b>Kilometers: </b>{{ car.7 }}</p>
                    <p class="m-1"><b>Price: </b>{{ car.5 }}</p>
                </div>
                    {% else %}
                                    <div class="col-sm">
                    <img style="text-align: center;" src="{% static 'car2.jpeg' %}" width="150" height="150"
                        alt="">
                    <p class="mt-2 m-1 "><b>Plate: </b>{{ car.0 }}</p>
                    <p class="m-1"><b>Daily Price: </b> {{ car.2}}</p>
                    <p class="m-1"><b>Model: </b>{{ car.3 }}</p>
                    <p class="m-1"><b>Age: </b>{{ car.6 }}</p>
                    <p class="m-1"><b>Kilometers: </b>{{ car.7 }}</p>
                    <p class="m-1"><b>Price: </b>{{ car.5 }}</p>
                </div>
                {% endif %}

            {% endfor %}
            </div></div></div>
{% endblock %}

templates/chauffeurDashboard.html
{% extends 'chauffeurBase.html' %}
{% block content %}
{% if request.session.user_type == 'chauffeur' %}
<div class="container">
    <div class="row mt-5">
       <h1> Chauffeur Requests</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Reservation Number</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Employee Status</th>
                    <th scope="col">Reserver</th>
                    <th scope="col">Checked By</th>
                    <th scope="col">License Place</th>
                    <th scope="col">Approve</th>
                    <th scope="col">Deny</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
            {% for request in chauffeur_requests %}
            {% if request.3 != "canceled" %}
            <tr>
                <td>{{request.0}}</td>
                <td>{{request.1}}</td>
                <td>{{request.2}}</td>
                <td>{{request.3}}</td>
                <td>{{request.4}}</td>
                <td>{{request.5}}</td>
                <td>{{request.6}}</td>
                {% if request.7 == None and request.3 == "accepted" %}
                <td><button type="button" value='{{ request.0 }}' class="btn btn-outline-success" >Accept</button></td>
                <td><button type="button" value='{{ request.0 }}' class="btn btn-outline-danger" >Reject</button></td>
                {% else %}
                <td><button type="button" value='{{ request.0 }}' class="btn btn-outline-success" disabled>Accept</button></td>
                <td><button type="button" value='{{ request.0 }}' class="btn btn-outline-danger" disabled>Reject</button></td>
                {% endif %}
                {% if request.7 == 1%}
                <td>Accepted</td>
                {% endif %}
                {% if request.7 == 0%}
                <td>Rejected</td>
                {% endif %}
                {% if request.7 == None and request.3 == "not_accepted"%}
                <td>Waiting for employee approval</td>
                {% endif %}
                {% if request.7 == None and request.3 == "accepted"%}
                <td>Waiting for your approval</td>
                {% endif %}
            </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script>
    console.log('script exectued');

    $(".btn-outline-success").on("click", function () {
      var reservationtId = $(this).val();
      var logged_in = $('#session').val();

      $.ajax({
        url: '/chauffeur/ajaxAcceptRequest',
        data: {
          'reservation_id': reservationtId,
          'chauffeur_id': logged_in,
        },
        dataType: 'json',
        success: function () {
              alert('you accepted the request');
              location.reload();
        }
      });

    });
  </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script>
    $(".btn-outline-danger").on("click", function () {
      var reservationtId = $(this).val();
      var logged_in = $('#session').val();

      $.ajax({
        url: '/chauffeur/ajaxDeclineRequest',
        data: {
          'reservation_id': reservationtId,
          'chauffeur_id': logged_in,
        },
        dataType: 'json',
        success: function () {
              alert('you declined the request');
              location.reload();
        }
      });

    });
    </script>

{% endblock %}

templates/customerDashboard.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
       <h1> Vehicles that you can rent.</h1>
        <table>
            {% for vehicle in vehicles %}
            {% if forloop.counter0|divisibleby:4 %}
            <tr>
                {% endif %}
                <td>
                    <p class="mt-2 m-1"><b>Plate: </b> {{vehicle.1}}</p>
                    <p class="m-1"><b>Status: </b> {{vehicle.2}}</p>
                    <p class="m-1"><b>Daily Price: </b> {{vehicle.3}}</p>
                    <p class="m-1"><b>Age: </b>{{vehicle.7}}</p>
                    <p class="m-1"><b>Kilometers: </b>{{vehicle.8}} km</p>
                    <p class="m-1"><b>Brand: </b>{{vehicle.5}}</p>
                    <p class="m-1"><b>Model: </b>{{vehicle.4}}</p>
                    <p class="m-1"><b>Branch: </b>{{vehicle.12}}</p>
                    <form action="{% url 'customer:customer_dashboard' %}" method='post'>
                        {% csrf_token %}
                        <input type='hidden' name="plate" value="{{ vehicle.1 }}"/>
                        <button type="submit" class="btn btn-success">Rent</button>
                    </form>
                </td>
                {% if forloop.counter|divisibleby:4 or forloop.last %}
            </tr>
            {% endif %}
            {% endfor %}
            </tr>
        </table>
        <div class="row" style="margin: 30px">
            <div class="col-lg">
                <table class="table">
              <thead>
               Your information about related branches
                <tr>
                  <th scope="col">Branch Name</th>
                    <th scope="col">Number of Reservations</th>
                  <th scope="col">Your Rating for Branch</th>
                    <th scope="col"> Your average expense on branch</th>
                </tr>
              </thead>
              <tbody>
              {% for value in info %}
                  <tr>
                  <th scope="row">{{ value.0 }}</th>
                  <td>{{ value.1 }}</td>
                  <td>{{ value.2 }}</td>
                  <td>{{ value.3 }}</td>
                </tr>
              {% endfor %}

              </tbody>
            </table>

            </div>
          </div></div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/customerRegister.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="row mt-5">
            <div class="col-3"></div>
            <div class="col-6">
                <h1 style="text-align: center;font-size: 20px;" class="display-1" >Customer Register Page</h1>
            <form action="{% url 'customer_register' %}" method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" class='btn btn-primary mt-3 btn-lg btn-block'value="Submit">
            </form></div>
                <div class="col-3"></div>

    </div>
{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

templates/customerRequest.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-1"></div>
       <div class="col-sm-6">
            <h1> Create Transfer Request</h1>
            <form action="{% url 'customer:customer_create_request' %}" method="post" id="create-request">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success mt-3">Request</button>
            </form>
            {% include 'messages.html' %}
            <p class="mt-3" style="color:green;">{{ message }}</p>
        </div>
        <div class="col-sm-1"></div>
        <div class="col-sm-4">
            <h2>Previous Requests</h2>
            {% for request in old_req %}
                {% if forloop.counter|divisibleby:"5" %}
                    <div class="row mt-4">
                                    <p class="col-sm">
                    <p class="mt-2 m-1 "><b>Car: </b>{{ request.4 }}</p>
                    <p class="mt-2 m-1 "><b>From Branch: </b>{{ request.9 }}</p>
                    <p class="m-1"><b>To Branch: </b> {{ request.11}}</p>
                    <p class="m-1"><b>Status: </b>
                        {% if request.6 == 1 %}
                            Accepted
                            {% else %}
                            Not Accepted
                            {% endif %}</p>
                    <p class="m-1"><b>Reason: </b>{{ request.7 }}</p>
                </div>
                    {% else %}
                                    <div class="col-sm">
                    <p class="col-sm">
                        <p class="mt-2 m-1 "><b>Car: </b>{{ request.4 }}</p>
                        <p class="mt-2 m-1 "><b>From Branch: </b>{{ request.9 }}</p>
                        <p class="m-1"><b>To Branch: </b> {{ request.11}}</p>
                        <p class="m-1"><b>Status: </b>
                            {% if request.6 == 1 %}
                                Accepted
                                {% else %}
                                Not Accepted
                                {% endif %}</p>
                        <p class="m-1"><b>Reason: </b>{{ request.7 }}</p>
                </div>
                {% endif %}

            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
 $('#create-request').submit(function() {
    var decision = window.confirm('Are you sure to make this request?');
    return decision;
});
</script>
{% endblock %}

templates/customerbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Carent</title>
</head>
<style>

</style>
{% block style %}
{% endblock %}
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a href="{% url 'customer:customer_dashboard' %}">
        <img src="{% static 'icon.png' %}" alt="" width="50" height="50" class="d-inline-block align-text-top"> </a>
        <a class="navbar-brand" href="{% url 'customer:customer_dashboard' %}">CaRent</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:reservation_list' %}">See Your
                        Reservations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_dashboard' %}">Vehicles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_create_request' %}">Create
                        Request</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_rate_vehicle' %}">Rate
                        Vehicles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_rate_branch' %}">Rate
                        Branch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer_return_vehicle' %}">Return
                        Vehicle</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:customer-penalties' %}">Penalties</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customer:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>
{% block scripts %}
{% endblock %}
</html>

templates/error.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-12">
            <div class="alert alert-danger" role="alert">
                Some Errors are occured. {{ message }}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/errorDate.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-12">
            <div class="alert alert-danger" role="alert">
                Please select valid start and end dates. {{ message }}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/listPenalties.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-9">
            <h1>Your Penalties</h1>
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Vehicle Plate</th>
                    <th scope="col">Description</th>
                    <th scope="col">Expertise</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Pay</th>
                </tr>
                </thead>
                <tbody>
                {% for pen in penalties %}
                <tr>
                    <th scope="row">{{ pen.0 }}</th>
                    <td>{{ pen.4 }}</td>
                    <td>{{ pen.1 }}</td>
                    <td>{{ pen.3 }}</td>
                    <td>{{ pen.2 }}</td>
                    <td>
                        <form action="{% url 'customer:customer-penalties' %}" method='post'>
                            {% csrf_token %}
                            {{ form }}
                            <input type='hidden' name="issueId" value="{{ pen.0 }}"/>
                            <button type="submit" class="btn btn-success">Pay</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include 'messages.html' %}
        <p class="mt-3" style="color:green;">{{ message }}</p>
    </div>
</div>
{% endif %}
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-dismissible {{ message.tags }} mt-3">
    <strong>{{message}}</strong>
</div>
{% endfor %}
{% endif %}

templates/ratevehicles.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-8">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Vehicle Plate</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Cost</th>
                </tr>
                </thead>
                <tbody>
                {% for res in old_res %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ res.10 }}</td>
                    <td>{{ res.1 }}</td>
                    <td>{{ res.2 }}</td>
                    <td>{{ res.4 }}$</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            <h4>Rate Vehicle</h4>
            <form action="{% url 'customer:customer_rate_vehicle' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success mt-3">Evaluate</button>
            </form>
            {% include 'messages.html' %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/reservationcomplate.html
{% extends 'customerbase.html' %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-12">
            <div class="alert alert-success" role="alert">
                Reservation is taken. Thank you.
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/returnvehicles.html
{% extends 'customerbase.html' %}
{% block content %}
{% if request.session.user_type == 'customer' %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-3">
            <h4>Status: {{ user_status }}</h4>
            <h4>Discount Rate: {{ discount_rate }}%</h4>
        </div>
        <div class="col-sm-9">
            <h1>Return Vehicle</h1>
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Vehicle Plate</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Status</th>
                    <th scope="col">Penalty</th>
                </tr>
                </thead>
                <tbody>
                {% for res in old_res %}
                <tr>
                    <th scope="row">{{ res.0 }}</th>
                    <td>{{ res.1 }}</td>
                    <td>{{ res.2 }}</td>
                    <td>{{ res.3 }}</td>
                    <td>{{ res.4 }}$</td>
                    <td>{{ res.5 }}</td>
                    <td>
                        <form action="{% url 'customer:customer_return_vehicle' %}" method='post'>
                            {% csrf_token %}
                            <input type='hidden' name="ReservationNo" value="{{ res.0 }}"/>
                            <button type="submit" class="btn btn-success">Pay</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}